# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Morozov
email: m.e.morozov1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science BA at Iona College, Metallurgy of nonferrous metals at Moscow Institute of Steel and Alloys. Currently living in Moscow, Russia. Building a career in technology. ğŸŒ
baseurl: #"/blog"
url: "https://mikefrosov.github.io/" # the base hostname & protocol for your site
github_username:  mikefrostov

# Build settings
#markdown: kramdown
