# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Morozov
email: no0bRus7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science student at Iona College, currently residing in Moscow, Russia. Starting career as a Web Programmer ğŸŒ
baseurl: #"/blog"
url: "http://blog.no0bRus.com" # the base hostname & protocol for your site
twitter_username: mishamishaco
github_username:  no0bRus

# Build settings
#markdown: kramdown
